spring:
  application:
    name: mindmap-service
  neo4j:
    uri: bolt://neo4j:7687
    authentication:
      username: ${MINDMAP_USER}
      password: ${MINDMAP_PASS}
management:
  endpoints:
    web:
      base-path: /api/mindmap/v1/actuator
server:
  port: ${SERVER_PORT}
  address: ${SERVER_ADRESS}
jwt:
  secret: ${JWT_SECRET}
adapter:
  uri:
    modul: https://studyhuppy.de/api/modul/v1