spring:
  application:
    name: mindmap-service
  neo4j:
    uri: bolt://localhost:${DB_PORT}
    authentication:
      username: ${MINDMAP_USER}
      password: ${MINDMAP_PASS}
management:
  endpoints:
    web:
      base-path: /api/mindmap/v1/actuator
server:
  port: ${DEV_SERVER_PORT}
jwt:
  secret: ${JWT_SECRET}
adapter:
  uri:
    modul: http://localhost:9502/api/modul/v1