spring:
  application:
    name: studyhub-auth-service
  datasource:
    url: jdbc:postgresql://user-db:5432/${AUTH_DB}
    username: ${AUTH_DB_USER}
    password: ${AUTH_DB_PASS}
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: ${SERVER_PORT}
  address: ${SERVER_ADRESS}
jwt:
  secret: ${JWT_SECRET}
  role:
    admin:
      username: ${ADMIN}
mail:
  api-url: https://studyhuppy.de/api/mail/v1
kartei:
  api-url: https://studyhuppy.de/api/kartei/v1
modul:
  api-url: https://studyhuppy.de/api/modul/v1
mindmap:
  api-url: https://studyhuppy.de/api/mindmap/v1