spring:
  application:
    name: studyhub-auth-service
  datasource:
    url: jdbc:postgresql://user-db:5432/${AUTH_DB}
    username: ${AUTH_DB_USER}
    password: ${AUTH_DB_PASS}
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: ${SERVER_PORT}
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: ${KEY_STORE_PASS}
    key-store-type: PKCS12
    key-alias: tomcat
jwt:
  secret: ${JWT_SECRET}
  role:
    admin:
      username: ${ADMIN}