spring:
  application:
    name: studyhub-auth-service
  datasource:
    url: jdbc:postgresql://localhost:6436/${AUTH_DB}
    username: ${AUTH_DB_USER}
    password: ${AUTH_DB_PASS}
  kafka:
    bootstrap-servers: localhost:10000
    consumer:
      group-id: studyhuppy
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
management:
  endpoints:
    web:
      base-path: /api/auth/v1/actuator
      exposure:
        include: "*"
server:
  port: ${SERVER_PORT}
jwt:
  secret: ${JWT_SECRET}
  role:
    admin:
      username: ${ADMIN}
mail:
  api-url: http://localhost:9083/api/mail/v1
kartei:
  api-url: http://localhost:9081/api/kartei/v1
modul:
  api-url: http://localhost:9080/api/modul/v1
mindmap:
  api-url: http://localhost:9087/api/mindmap/v1
