pipeline {
    agent any

    environment {
        SERVICE = 'modul-service'
    }

    stages {
        stage("Führe Tests für ${SERVICE} aus") {
            steps {
                sh 'mvn clean test'
            }
        }
    }
}
