pipeline {
    agent any

    environment {
        SERVICE = 'modul-service'
    }

    stages {
        stage('Führe Tests aus') {
            steps {
                echo "Starte Tests für ${SERVICE}"
                sh 'mvn clean test'
            }
        }
    }
}
