spring:
  application:
    name: studyhub-auth-service
  datasource:
    url: jdbc:postgresql://localhost:${AUTH_DB_HOST_PORT}/${AUTH_DB}
    username: ${AUTH_DB_USER}
    password: ${AUTH_DB_PASS}
management:
  endpoints:
    web:
      base-path: /api/auth/v1/actuator
      exposure:
        include: "*"
server:
  port: ${DEV_SERVER_PORT}
jwt:
  secret: ${JWT_SECRET}
  role:
    admin:
      username: ${ADMIN}
mail:
  api-url: http://localhost:9510/api/mail/v1
kartei:
  api-url: http://localhost:9503/api/kartei/v1
modul:
  api-url: http://localhost:9502/api/modul/v1
mindmap:
  api-url: http://localhost:9504/api/mindmap/v1
