spring:
  application:
    name: actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /admin
  endpoint:
    health:
      show-details: always
  health:
    ssl:
      enabled: false
    ping:
      enabled: false
    diskspace:
      enabled: false
info:
  app:
    name: "Actuator"
    description: "Actuator Service"
    version: "1.0.0"
server:
  port: ${DEV_SERVER_PORT}
app:
  metrics:
    modul: http://studyhuppy.de/api/modul/v1/actuator/metrics/http.server.requests
    kartei: http://studyhuppy.de/api/kartei/v1/actuator/metrics/http.server.requests
    mail: http://studyhuppy.de/api/mail/v1/actuator/metrics/http.server.requests
    authentication: http://studyhuppy.de/api/auth/v1/actuator/metrics/http.server.requests
    mindmap: http://studyhuppy.de/api/mindmap/v1/actuator/metrics/http.server.requests
  health:
    service:
      modul: http://studyhuppy.de/api/modul/v1/actuator/health
      kartei: http://studyhuppy.de/api/kartei/v1/actuator/health
      mail: http://studyhuppy.de/api/mail/v1/actuator/health
      authentication: http://studyhuppy.de/api/auth/v1/actuator/health
      mindmap: http://studyhuppy.de/api/mindmap/v1/actuator/health
    db:
      modul: http://studyhuppy.de/api/modul/v1/get-db-health
      kartei: http://studyhuppy.de/api/kartei/v1/get-db-health
      mail: http://studyhuppy.de/api/mail/v1/get-db-health
      authentication: http://studyhuppy.de/api/auth/v1/get-db-health
      mindmap: http://studyhuppy.de/api/mindmap/v1/get-db-health
  api:
    token: ${ACTUATOR_API_KEY}