spring:
  application:
    name: mail
  mail:
    host: smtp.example.com
    port: 587
    username: ${MAIL_MAIN_EMAIL}
    password: ${MAIL_MAIN_PASS}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  datasource:
    password: ${MAIL_DB_PASS}
    username: ${MAIL_DB_USER}
    url: jdbc:postgresql://mail-db:5432/${MAIL_DB}
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 9083
application:
  mail:
    address: ${MAIL_MAIN_EMAIL}
kartei:
  api-url: https://studyhuppy.de/api/kartei/v1
auth:
  api-url: https://studyhuppy.de/api/auth/v1