spring:
  application:
    name: mail
  mail:
    host: localhost
    port: 1025
    username: timo
    password: 1234
  datasource:
    password: ${DB_PASS}
    username: ${DB_USER}
    url: jdbc:postgresql://localhost:6435/mail
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 9083
application:
  mail:
    address: "example@web.de"