spring:
  sql:
    init:
      mode: always
      platform: postgresql
  jpa:
    show-sql: true
  application:
    name: kartei
  datasource:
    password: ${KARTEI_DB_PASS}
    username: ${KARTEI_DB_USER}
    url: jdbc:postgresql://kartei-db:${PG_PORT}/${KARTEI_DB}
  security:
    user:
      name: none
      password: none
      role: none
management:
  endpoints:
    web:
      base-path: /api/kartei/v1/actuator
      exposure:
        include: "*"
  tracing:
    enabled: true
  endpoint:
    httpexchanges:
      access: read_only
server:
  port: ${PROD_SERVER_PORT}
  address: ${SERVER_ADRESS}
jwt:
  secret: ${JWT_SECRET}