spring:
  sql:
    init:
      mode: always
      platform: postgresql
  jpa:
    show-sql: true
  application:
    name: kartei
  datasource:
    password: ${DB_PASS}
    username: ${DB_USER}
    url: jdbc:postgresql://localhost:6434/kartei
  security:
    user:
      name: none
      password: none
      role: none
management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    enabled: true
  endpoint:
    httpexchanges:
      access: read_only
server:
  port: 9081
jwt:
