spring:
  application:
    name: studytracker
  datasource:
    password: ${DB_PASS}
    username: ${DB_USER}
    url: jdbc:postgresql://localhost:6433/tracker
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GIT_CLIENT}
            client-secret: ${GIT_SECRET}
            scope: read:user
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
    user:
      name: none
      password: none
      role: none
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 9080
logging:
  level:
    org:
      springframework:
        security:
jwt:
  secret: ${JWT_SECRET}