spring:
  application:
    name: modul
  datasource:
    password: ${MODUL_DB_PASS}
    username: ${MODUL_DB_USER}
    url: jdbc:postgresql://localhost:6433/${MODUL_DB}
  security:
    user:
      name: none
      password: none
      role: none
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: ${SERVER_PORT}
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: ${DEV_KEYSTORE_PASS}
    key-store-type: PKCS12
    key-alias: springboot

jwt:
  secret: ${JWT_SECRET}
maxModule: 30