spring:
  application:
    name: studytracker
  datasource:
    password: ${DB_PASS}
    username: ${DB_USER}
    url: jdbc:postgresql://localhost:6433/modul
  security:
    user:
      name: none
      password: none
      role: none
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 9080
logging:
  level:
    org:
      springframework:
        security:
jwt:
  secret: ${JWT_SECRET}
maxModule: 30