spring:
  application:
    name: actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /admin
  endpoint:
    health:
      show-details: always
  health:
    ssl:
      enabled: false
    ping:
      enabled: false
    diskspace:
      enabled: false
info:
    app:
        name: "Actuator"
        description: "Actuator Service"
        version: "1.0.0"
server:
  port: 9085
app:
  metrics:
    track: http://localhost:8080/actuator/metrics/http.server.requests
    kartei: http://localhost:8081/actuator/metrics/http.server.requests
    mail: http://localhost:8083/actuator/metrics/http.server.requests
    authentication: http://localhost:8084/actuator/metrics/http.server.requests
  services:
    health:
        track: http://localhost:8080/actuator/health
        kartei: http://localhost:8081/actuator/health
        mail: http://localhost:8083/actuator/health
        authentication: http://localhost:8084/actuator/health

