spring:
  application:
    name: mail
  mail:
    host: localhost
    port: ${SMTP_PORT}
    username: timo
    password: 1234
  datasource:
    password: ${MAIL_DB_PASS}
    username: ${MAIL_DB_USER}
    url: jdbc:postgresql://localhost:${MAIL_DB_HOST_PORT}/${MAIL_DB}
management:
  endpoints:
    web:
      base-path: /api/mail/v1/actuator
      exposure:
        include: "*"
server:
  port: ${DEV_SERVER_PORT}
application:
  mail:
    address: ${MAIL_MAIN_EMAIL}
kartei:
  api-url: http://localhost:9503/api/kartei/v1
auth:
  api-url: http://localhost:9501/api/auth/v1