pipeline {
    agent any

    environment {
        SERVICE = 'mail-service'
    }

    tools {
            maven "M3"
    }

    stages {
        stage('Führe Tests aus') {
            steps {
                dir('backend/mail') {
                    echo "Starte Tests für ${SERVICE}"
                    bat 'mvn clean test'
                }
            }
        }
    }
}
