spring:
  profiles:
    active: native
  application:
    name: studyhuppy-config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations
server:
  port: 9505
