name: actuator
services:
  actuator-service:
    container_name: actuator_service
    build:
      dockerfile: Dockerfile
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - SERVER_ADRESS=${SERVER_ADRESS}
      - JWT_SECRET=${JWT_SECRET}
    env_file:
      - .env