spring:
  application:
    name: mindmap-service
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: ${MINDMAP_USER}
      password: ${MINDMAP_PASS}
management:
  endpoints:
    web:
      base-path: /api/mindmap/v1/actuator
server:
  port: ${SERVER_PORT}
jwt:
  secret: ${JWT_SECRET}