name: Build and Test Authentication Service

on:
  push:
    paths:
      - 'authentication/**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PG_PORT: ${{ secrets.PG_PORT }}
      AUTH_DB_HOST_PORT: ${{ secrets.AUTH_DB_HOST_PORT }}
      SERVER_PORT: ${{ secrets.SERVER_PORT }}

      JWT_SECRET: ${{ secrets.JWT_SECRET }}

      AUTH_DB: ${{ secrets.AUTH_DB }}
      AUTH_DB_USER: ${{ secrets.AUTH_DB_USER }}
      AUTH_DB_PASS: ${{ secrets.AUTH_DB_PASS }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create .env file for service
        run: |
          echo "PG_PORT=${PG_PORT}" >> authentication/.env
          echo "AUTH_DB_HOST_PORT=${AUTH_DB_HOST_PORT}" >> authentication/.env
          echo "SERVER_PORT=${SERVER_PORT}" >> authentication/.env
          echo "JWT_SECRET=${JWT_SECRET}" >authentication/.env
          echo "AUTH_DB=${AUTH_DB}" >> authentication/.env
          echo "AUTH_DB_USER=${AUTH_DB_USER}" >> authentication/.env
          echo "AUTH_DB_PASS=${AUTH_DB_PASS}" >> authentication/.env

      - name: Start service with Docker Compose
        run: docker compose -f authentication/docker-compose.yaml up -d --build