name: Build Angular App

on:
  push:
    paths:
      - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Change directory to frontend
        run: cd frontend

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npx build --configuration production