name: Build and Test Mail Service

on:
  push:
    paths:
      - 'mail/**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PG_PORT: ${{ secrets.PG_PORT }}
      MAIL_DB_HOST_PORT: ${{ secrets.MAIL_DB_HOST_PORT }}
      SERVER_PORT: ${{ secrets.SERVER_PORT }}

      JWT_SECRET: ${{ secrets.JWT_SECRET }}

      MAIL_DB: ${{ secrets.MAIL_DB }}
      MAIL_DB_USER: ${{ secrets.MAIL_DB_USER }}
      MAIL_DB_PASS: ${{ secrets.MAIL_DB_PASS }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create .env file for service
        run: |
          echo "PG_PORT=${PG_PORT}" >> mail/.env
          echo "MAIL_DB_HOST_PORT=${MAIL_DB_HOST_PORT}" >> mail/.env
          echo "SERVER_PORT=${SERVER_PORT}" >> mail/.env
          echo "JWT_SECRET=${JWT_SECRET}" >mail/.env
          echo "MAIL_DB=${MAIL_DB}" >> mail/.env
          echo "MAIL_DB_USER=${MAIL_DB_USER}" >> mail/.env
          echo "MAIL_DB_PASS=${MAIL_DB_PASS}" >> mail/.env

      - name: Start service with Docker Compose
        run: docker compose -f mail/docker-compose.yaml up -d --build