name: Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        name: Git Checkout
      - name: Java installieren
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Make mvnw executable
        run: chmod +x ./mvnw
      - name: Run Maven
        run: ./mvnw clean install
      
